# Generated by Django 2.2.1 on 2020-05-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Details',
        ),
    ]
