# Generated by Django 2.2.9 on 2020-04-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_msgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
